[package]
name = "mint-rust-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.9", features = ["blocking", "json"]}
serde = "1.0.216"
serde_json = "1.0.134"
thiserror = "2.0.9"
